export const workExperience = [
  {
    title: "Full Stack Developer",
    company: "LifeBeyondClass",
    Link: "https://lifebeyondclass.com/",
    date: "September 2023 - Present",
    description: `Worked with a team of developers to create an LMS platform`,
    skills: [
      "Typescript",
      "ReactJS",
      "NextJS",
      "NodeJS",
      "AdonisJS",
      "MongoDB",
      "AWS",
    ],
  },
  {
    title: "Full Stack Developer (Internship)",
    company: "Handiwoker Tech",
    date: "March 2023 - September 2023",
    description: `Developed`,
    skills: [
      "Typescript",
      "ReactJS",
      "NextJS",
      "NodeJS",
      "AdonisJS",
      "MongoDB",
      "AWS",
      "Styled-components",
      "Storybook",
    ],
  },
];
